### ISSUE TITLE
PyPi package?

### ISSUE THREAD

**Issue by jwlodek** [max-dotpy/GUI_maker#2]
Any chance this project could be reformatted into a PyPi project I could install with 
```
pip install gui-maker
```
and then run it with
```
gui-maker
```
or something like that?

I can help out with this if you would like.

**Comment by max-dotpy** [comment]
Honestly I don't know how to do that, I'll read about it. But yeah it'd be great! Any help is greatly appreciated

**Comment by jwlodek** [comment]
I'll take a look at doing this tm, and I'll make a pull request. I'll explain what changes I made to make it work as well. The main codebase shouldnt need to change.

**Comment by max-dotpy** [comment]
Thank you! I've read about it and I should be able to prepare it myself, if you prefer. Though I don't know how to run it through terminal with "gui-maker" command

**Comment by jwlodek** [comment]
Of course if you wanted to do it yourself that would be great. For the `gui-maker`, in your setup.py file for the packaging, just add an `entry-point` as a console script, pointing at the main function to start your program, and you can name it `gui-maker` or whatever you would like.

**Comment by max-dotpy** [comment]
I tried, is this correct? I wasn't able to add the entry point though, I'll wait for you before publishing to PyPi

**Comment by jwlodek** [comment]
You can check if it works by running 
```
pip install .
```
in the project directory. For entry points, it should be this:
```
    entry_points={
        'console_scripts': [
            'GUICoder= GUICoder.app:main',
        ],
    },
```
You will just have to move the contents of `if __name__ == '__main__':` to a `main()` function, and then call that in `if __name__ == '__main__':`

**Comment by max-dotpy** [comment]
I tried but it gives me this error:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/GUIcoder", line 6, in <module>
    from GUICoder.app import main
ModuleNotFoundError: No module named 'GUICoder'`
Problem is I don't get where it takes GUICoder (with the capital C) from.. 
Can you help?

**Comment by jwlodek** [comment]
Hi, not sure if you figured it out yourself already, but it all worked for me!

```
(PyEnv) E:\ProgrammingWorkspace>git clone https://github.com/max-dotpy/GUI_maker
Cloning into 'GUI_maker'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 104 (delta 49), reused 64 (delta 22), pack-reused 0
Receiving objects: 100% (104/104), 24.17 MiB | 5.26 MiB/s, done.
Resolving deltas: 100% (49/49), done.

(PyEnv) E:\ProgrammingWorkspace>cd GUI_maker

(PyEnv) E:\ProgrammingWorkspace\GUI_maker>ls
GUIcoder  LICENSE.txt  README.md  README.txt  requirements.txt  setup.cfg.txt  setup.py  simple_demonstration.mov

(PyEnv) E:\ProgrammingWorkspace\GUI_maker>pip install .
Processing e:\programmingworkspace\gui_maker
Collecting Pillow
  Downloading Pillow-7.0.0-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 3.3 MB/s
Collecting pyperclip
  Downloading pyperclip-1.7.0.tar.gz (15 kB)
Installing collected packages: Pillow, pyperclip, GUIcoder
    Running setup.py install for pyperclip ... done
    Running setup.py install for GUIcoder ... done
Successfully installed GUIcoder-0.1 Pillow-7.0.0 pyperclip-1.7.0

(PyEnv) E:\ProgrammingWorkspace\GUI_maker>py
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GUIcoder
>>> exit()

(PyEnv) E:\ProgrammingWorkspace\GUI_maker>GUIcoder

(PyEnv) E:\ProgrammingWorkspace\GUI_maker>
```
And the program opened up like normal

**Comment by max-dotpy** [comment]
I needed to update the version number and delete the previous "entrypoint exec file". Now it seems to be working fine. Thank you !!

**Comment by jwlodek** [comment]
No problem! Will use this for sure, much easier to work with if I can just do `pip install` now
